# netlify.toml — simples e sem erro de headers

[build]
  # Remova "base" para não dar frontend/frontend em dev
  publish = "frontend"
  command = ""

# Proxy da API no Railway
[[redirects]]
  from = "/api/*"
  to = "https://clube-vantagens-api-production.up.railway.app/:splat"
  status = 200
  force = true

# (Opcional) Se quiser headers, use SEMPRE array de tabelas:
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Cache-Control = "public, max-age=0, must-revalidate"
