[build]
  publish = "frontend"
  command = ""

# --- atalhos sem /api (precisam vir antes de qualquer wildcard /*) ---
[[redirects]]
from = "/planos"
to   = "/api/planos"
status = 200
force = true

[[redirects]]
from = "/planos/"
to   = "/api/planos"
status = 200
force = true

[[redirects]]
from = "/planos/*"
to   = "/api/planos/:splat"
status = 200
force = true

# proxy da API na Railway (manter)
[[redirects]]
from = "/api/*"
to   = "https://clube-vantagens-api-production.up.railway.app/:splat"
status = 200
force  = true

[[redirects]]
from = "/admin/*"
to   = "https://clube-vantagens-api-production.up.railway.app/admin/:splat"
status = 200
force  = true

[[redirects]]
from = "/testar-cadastro"
to = "/admin/cadastro"
status = 301

# QUALQUER catch-all fica POR ÚLTIMO
# [[redirects]]
#   from = "/*"
#   to   = "/index.html"
#   status = 200
