[build]
  publish = "frontend"
  command = ""

# --- Proxies para a API no Railway ---
# API pública: https://clube-vantagens-api-production.up.railway.app

# atalhos sem /api
[[redirects]]
from = "/planos"
to   = "/api/planos"
status = 200
force = true

[[redirects]]
from = "/planos/"
to   = "/api/planos"
status = 200
force = true

[[redirects]]
from = "/planos/*"
to   = "/api/planos/:splat"
status = 200
force = true

# proxy geral da API
[[redirects]]
from = "/api/*"
to   = "https://clube-vantagens-api-production.up.railway.app/:splat"
status = 200
force  = true

[[redirects]]
from = "/admin/*"
to   = "https://clube-vantagens-api-production.up.railway.app/admin/:splat"
status = 200
force  = true

[[redirects]]
from = "/testar-cadastro"
to = "/admin/cadastro"
status = 301
