### Consulta cliente
GET http://localhost:3000/assinaturas?cpf=12345678900

### Registrar transação
POST http://localhost:3000/transacao
Content-Type: application/json

{
  "cpf": "12345678900",
  "valor": 250.00
}
